version: 2.1

executors:
  build-test-and-publish:
    docker:
      - image: circleci/node:10.14.1
        environment:
          TEST_DB_HOST: localhost
          TEST_DB_TYPE: postgres
          TEST_DB_NAME: circle-test
          TEST_DB_USERNAME: root

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test

      - image: circleci/mysql:5.7.26

    working_directory: ~/repo

jobs:
  build:
    executor: build-test-and-publish
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Run tests with Postgres
          command: yarn test
      - run:
          name: Run tests with Mysql
          command: TEST_DB_TYPE=mysql TEST_DB_NAME=circle_test TEST_DB_HOST=127.0.0.1 TEST_DB_PORT=3306 yarn test

      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    executor: build-test-and-publish
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run: npm publish --access public

workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
